"use client";
import { useEffect, useState } from "react";

type Lead={id:string;customer_name?:string;customer_email?:string;customer_phone?:string;question:string;action?:string;status:string;created_at:string};
type Data={totals:{total:number;last_24h:number;last_7d:number;identified:number};actions:{action:string;count:number}[];statuses:{status:string;count:number}[];recent:Lead[];daily:{day:string;count:number}[]};

const navy="#002F5B", blue="#0066A1", sky="#00A3E0", ink="#17324D", muted="#64798A", line="#D7E7F0", light="#EAF6FB";

export default function AdminPage(){
 const[key,setKey]=useState(""); const[savedKey,setSavedKey]=useState(""); const[data,setData]=useState<Data|null>(null); const[loading,setLoading]=useState(false); const[error,setError]=useState("");
 async function load(k=savedKey){if(!k)return;setLoading(true);setError("");try{const r=await fetch("/api/admin/analytics",{headers:{"x-admin-key":k},cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error||"Unauthorized");setData(j);setSavedKey(k);}catch(e){setError(e instanceof Error?e.message:"Unable to load dashboard");setData(null)}finally{setLoading(false)}}
 useEffect(()=>{const k=sessionStorage.getItem("kpia-admin-key")||"";if(k){setSavedKey(k);load(k)}},[]);
 function login(){sessionStorage.setItem("kpia-admin-key",key);load(key)}
 function logout(){sessionStorage.removeItem("kpia-admin-key");setSavedKey("");setData(null)}
 async function updateStatus(id:string,status:string){await fetch("/api/admin/analytics",{method:"PATCH",headers:{"Content-Type":"application/json","x-admin-key":savedKey},body:JSON.stringify({id,status})});load()}
 if(!data)return <main style={shell}><div style={card}><div style={badge}>KENTAINERS • ADMIN</div><h1 style={{margin:"15px 0 8px",color:ink}}>Enquiry & Lead Dashboard</h1><p style={{color:muted,lineHeight:1.55}}>Secure internal view of chatbot enquiries, lead activity and conversion status.</p><input value={key} onChange={e=>setKey(e.target.value)} onKeyDown={e=>e.key==="Enter"&&login()} type="password" placeholder="ADMIN_DASHBOARD_KEY" style={input}/><button onClick={login} disabled={!key||loading} style={button}>{loading?"Checking…":"Open dashboard"}</button>{error&&<p style={{color:"#A33",fontSize:13}}>{error}</p>}<p style={{fontSize:11,color:muted,marginTop:18}}>The dashboard key is never stored in the database; it is held only in this browser session.</p></div></main>;
 return <main style={shell}><div style={{maxWidth:1240,margin:"0 auto"}}><header style={{...card,background:`linear-gradient(135deg,${navy},${blue},${sky})`,color:"white",border:0}}><div style={{display:"flex",justifyContent:"space-between",gap:15,alignItems:"center",flexWrap:"wrap"}}><div><div style={{fontSize:11,fontWeight:900,letterSpacing:1}}>KENTAINERS PRODUCT CHATBOT</div><h1 style={{margin:"8px 0 4px"}}>Enquiry & Lead Dashboard</h1><div style={{opacity:.86,fontSize:13}}>Customer enquiries • lead activity • chatbot analytics</div></div><button onClick={logout} style={{...smallButton,background:"rgba(255,255,255,.14)",color:"white",border:"1px solid rgba(255,255,255,.25)"}}>Sign out</button></div></header>
 <section style={statsGrid}>{[["Total enquiries",data.totals.total],["Last 24 hours",data.totals.last_24h],["Last 7 days",data.totals.last_7d],["Identified leads",data.totals.identified]].map(([t,v])=><div style={card} key={String(t)}><div style={{fontSize:12,color:muted}}>{t}</div><div style={{fontSize:32,fontWeight:900,color:blue,marginTop:8}}>{v}</div></div>)}</section>
 <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(280px,1fr))",gap:14,marginBottom:14}}><div style={card}><h2 style={h2}>Lead status</h2>{data.statuses.map(x=><div style={barRow} key={x.status}><span>{x.status}</span><b>{x.count}</b></div>)}</div><div style={card}><h2 style={h2}>Chatbot actions</h2>{data.actions.map(x=><div style={barRow} key={x.action}><span>{x.action}</span><b>{x.count}</b></div>)}</div><div style={card}><h2 style={h2}>Last 14 days</h2>{data.daily.length?<div style={{display:"flex",alignItems:"end",gap:5,height:130}}>{data.daily.map(x=><div title={`${x.day}: ${x.count}`} key={x.day} style={{flex:1,height:`${Math.max(12,Math.min(100,x.count*14))}%`,background:`linear-gradient(${blue},${sky})`,borderRadius:"5px 5px 2px 2px"}}/> )}</div>:<p style={{color:muted}}>No activity yet.</p>}</div></section>
 <section style={card}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:10,marginBottom:12}}><h2 style={h2}>Recent customer enquiries</h2><button onClick={()=>load()} style={smallButton}>Refresh</button></div><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:13}}><thead><tr>{["Date","Customer","Contact","Question","Action","Status"].map(h=><th key={h} style={th}>{h}</th>)}</tr></thead><tbody>{data.recent.map(l=><tr key={l.id}><td style={td}>{new Date(l.created_at).toLocaleString("en-KE")}</td><td style={td}><b>{l.customer_name||"Not provided"}</b><div style={{fontSize:10,color:muted}}>{l.id}</div></td><td style={td}>{l.customer_email||"—"}<br/>{l.customer_phone||"—"}</td><td style={{...td,maxWidth:360}}>{l.question}</td><td style={td}>{l.action||"—"}</td><td style={td}><select value={l.status} onChange={e=>updateStatus(l.id,e.target.value)} style={select}>{["open","contacted","qualified","converted","closed"].map(s=><option key={s}>{s}</option>)}</select></td></tr>)}</tbody></table>{!data.recent.length&&<p style={{color:muted}}>No enquiries have been captured yet.</p>}</div></section>
 </div></main>
}
const shell={minHeight:"100vh",background:`linear-gradient(160deg,${light},#fff 45%,#F2F8FC)`,padding:"24px 14px",fontFamily:"Arial,Helvetica,sans-serif"};
const card={background:"rgba(255,255,255,.96)",border:`1px solid ${line}`,borderRadius:18,padding:20,boxShadow:"0 10px 30px rgba(0,47,91,.07)"};
const badge={display:"inline-block",fontSize:10,fontWeight:900,letterSpacing:1,color:blue,background:light,padding:"7px 10px",borderRadius:999};
const input={width:"100%",boxSizing:"border-box" as const,padding:13,border:`1px solid ${line}`,borderRadius:10,margin:"16px 0 10px",outline:"none",fontSize:14};
const button={width:"100%",padding:13,border:0,borderRadius:10,background:navy,color:"white",fontWeight:900,cursor:"pointer"};
const smallButton={padding:"9px 13px",border:`1px solid ${line}`,borderRadius:9,background:"white",fontWeight:800,color:navy,cursor:"pointer"};
const statsGrid={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:14,margin:"14px 0"};
const h2={fontSize:16,color:ink,margin:"0 0 14px"};
const barRow={display:"flex",justifyContent:"space-between",padding:"10px 0",borderBottom:`1px solid ${line}`,fontSize:13,color:ink};
const th={textAlign:"left" as const,padding:"10px 8px",borderBottom:`2px solid ${line}`,color:muted,fontSize:11};
const td={padding:"12px 8px",borderBottom:`1px solid ${line}`,verticalAlign:"top" as const,color:ink};
const select={padding:"7px",border:`1px solid ${line}`,borderRadius:8,color:ink,background:"white"};
