"use client";
import {useState} from "react";
type Message={role:"user"|"assistant";text:string;sources?:{document:string;page?:number}[]};
const starterQuestions=[
  "I need a 5,000 litre water storage tank",
  "Compare the 5,000 and 6,000 litre Kentank options",
  "I need a solution for a shallow well",
  "What Kentainers product is suitable for hand washing at a school?"
];
export default function Home(){const[input,setInput]=useState("");const[messages,setMessages]=useState<Message[]>([{role:"assistant",text:"Hello. I’m KPIA, the Kentainers Product Intelligence Agent. Tell me what the customer needs, and I’ll use the Kentainers catalogue to identify relevant options and ask for clarification when the requirement is ambiguous."}]);const[loading,setLoading]=useState(false);async function send(text?:string){const message=(text??input).trim();if(!message||loading)return;setInput("");setMessages(m=>[...m,{role:"user",text:message}]);setLoading(true);try{const res=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message})});const data=await res.json();setMessages(m=>[...m,{role:"assistant",text:data.answer,sources:data.sources}]);}catch{setMessages(m=>[...m,{role:"assistant",text:"The service is temporarily unavailable. Please try again."}]);}finally{setLoading(false);}}return <main style={{maxWidth:900,margin:"40px auto",padding:"0 20px"}}><div style={{background:"white",borderRadius:16,padding:28,boxShadow:"0 5px 25px rgba(0,0,0,.08)"}}><h1 style={{marginTop:0}}>Kentainers Product Intelligence Agent</h1><p style={{color:"#58636f"}}>Grounded product-selection support for Kentainers sales representatives.</p><div style={{margin:"18px 0 24px"}}><strong style={{fontSize:14}}>Try a question</strong><div style={{display:"flex",flexWrap:"wrap",gap:8,marginTop:10}}>{starterQuestions.map((q,i)=><button key={i} onClick={()=>send(q)} disabled={loading} style={{padding:"9px 12px",border:"1px solid #ccd3da",borderRadius:999,background:"#f8fafc",color:"#173f5f",cursor:loading?"not-allowed":"pointer"}}>{q}</button>)}</div></div><div style={{margin:"25px 0",minHeight:360}}>{messages.map((m,i)=><div key={i} style={{margin:"14px 0",padding:16,borderRadius:12,background:m.role==="user"?"#eef5ff":"#f3f5f7"}}><strong>{m.role==="user"?"You":"KPIA"}</strong><div style={{marginTop:8,whiteSpace:"pre-wrap"}}>{m.text}</div>{m.sources?.length?<div style={{marginTop:10,fontSize:12,color:"#566"}}>Sources: {m.sources.map((s,j)=><span key={j}>{s.document}{s.page?`, p.${s.page}`:""}{j<m.sources!.length-1?"; ":""}</span>)}</div>:null}</div>)}</div><div style={{display:"flex",gap:10}}><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="e.g. I need a 6,000 litre water storage tank" style={{flex:1,padding:14,border:"1px solid #ccd3da",borderRadius:10,fontSize:16}}/><button onClick={()=>send()} disabled={loading} style={{padding:"14px 20px",border:0,borderRadius:10,background:"#173f5f",color:"white",fontWeight:700}}>{loading?"Thinking...":"Ask KPIA"}</button></div></div></main>}
