"use client";
import {useState, type CSSProperties} from "react";

type Message={role:"user"|"assistant";text:string;enquiryId?:string};
type Requirements={product:string;capacity:string;application:string;location:string;quantity:string;timeframe:string};
const capabilities=[{icon:"◈",title:"Product Intelligence",text:"Find products by capacity, application, product code and customer requirement."},{icon:"▣",title:"Technical Q&A",text:"Ask technical questions and receive answers grounded in the Kentainers knowledge library."},{icon:"KSh",title:"Price Guidance",text:"Use indexed pricing evidence and request delivery location when a price is zonal."}];
const technicalQuestions=["What technical factors should I consider when selecting a tank?","What is the difference between the available tank applications?","What installation information is available for this product?","What are the key specifications of this product?"];
const brand={navy:"#002F5B",blue:"#0066A1",sky:"#00A3E0",light:"#EAF6FB",pale:"#F6FBFE",ink:"#17324D",muted:"#64798A",line:"#D7E7F0"};
const emptyRequirements:Requirements={product:"",capacity:"",application:"Domestic & Commercial",location:"",quantity:"",timeframe:""};
export default function Home(){
 const[input,setInput]=useState(""); const[customerName,setCustomerName]=useState(""); const[customerEmail,setCustomerEmail]=useState(""); const[customerPhone,setCustomerPhone]=useState(""); const[requirements,setRequirements]=useState<Requirements>(emptyRequirements); const[enquiryId,setEnquiryId]=useState(""); const[loading,setLoading]=useState(false);
 const[messages,setMessages]=useState<Message[]>([{role:"assistant",text:"Welcome to the Kentainers Product Chatbot. Kentainers products can be used for both domestic and commercial requirements. Capture the customer's details and requirement, then ask about a product, price, technical specification or application."}]);
 function setReq(key:keyof Requirements,value:string){setRequirements(r=>({...r,[key]:value}));}
 function newEnquiry(){setCustomerName("");setCustomerEmail("");setCustomerPhone("");setRequirements(emptyRequirements);setEnquiryId("");setInput("");setMessages([{role:"assistant",text:"New customer enquiry started. Kentainers products are available for domestic and commercial requirements. Capture the customer details and requirement, then ask your product or technical question."}]);}
 function useQuestion(question:string){setInput(question);window.setTimeout(()=>document.getElementById("chat-input")?.focus(),0);}
 async function send(){const question=input.trim();if(!question||loading)return;setInput("");setMessages(m=>[...m,{role:"user",text:question}]);setLoading(true);try{const res=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:question,customer:{name:customerName,email:customerEmail,phone:customerPhone},requirements,history:messages.slice(-12)})});const data=await res.json();if(data.enquiryId)setEnquiryId(data.enquiryId);setMessages(m=>[...m,{role:"assistant",text:data.answer||"I could not process that request.",enquiryId:data.enquiryId}]);}catch{setMessages(m=>[...m,{role:"assistant",text:"The service is temporarily unavailable. Please try again."}]);}finally{setLoading(false);}}
 return <main style={{minHeight:"100vh",background:`linear-gradient(160deg,${brand.light} 0%,#fff 42%,#F2F8FC 100%)`,padding:"20px 14px 46px",fontFamily:"Arial, Helvetica, sans-serif"}}><div style={{maxWidth:1180,margin:"0 auto"}}>
 <header style={{position:"relative",overflow:"hidden",borderRadius:24,padding:"30px 32px",background:`linear-gradient(135deg,${brand.navy} 0%,${brand.blue} 62%,${brand.sky} 100%)`,color:"white",boxShadow:"0 18px 45px rgba(0,47,91,.20)"}}><div style={{position:"relative",display:"flex",justifyContent:"space-between",gap:24,alignItems:"center",flexWrap:"wrap"}}><div><div style={{display:"inline-flex",padding:"7px 12px",borderRadius:999,background:"rgba(255,255,255,.13)",fontSize:11,fontWeight:900}}>KENTAINERS • PRODUCT INTELLIGENCE</div><h1 style={{fontSize:"clamp(29px,5vw,47px)",lineHeight:1.05,margin:"16px 0 9px"}}>Kentainers Product Chatbot</h1><p style={{maxWidth:720,fontSize:15.5,lineHeight:1.6,margin:0,color:"rgba(255,255,255,.90)"}}>Your digital assistant for Kentainers products, technical information, customer enquiries and verified price guidance.</p></div><div style={{minWidth:145,textAlign:"center",padding:"16px 18px",borderRadius:18,background:"rgba(255,255,255,.11)"}}><div style={{fontSize:27,fontWeight:900}}>KENTAINERS</div><div style={{fontSize:11,opacity:.82,marginTop:4}}>Knowledge Assistant</div></div></div></header>
 <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(230px,1fr))",gap:13,margin:"16px 0"}}>{capabilities.map(c=><div key={c.title} style={cardStyle}><div style={{fontSize:12,fontWeight:900,color:brand.blue}}>{c.icon}</div><h3 style={{margin:"8px 0 6px",fontSize:16,color:brand.ink}}>{c.title}</h3><p style={{margin:0,color:brand.muted,fontSize:13,lineHeight:1.5}}>{c.text}</p></div>)}</section>
 <section style={cardStyle}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,flexWrap:"wrap"}}><div><div style={{fontWeight:900,fontSize:16,color:brand.ink}}>Technical Q&A</div><div style={{fontSize:12,color:brand.muted,marginTop:3}}>Quick questions grounded in the Kentainers knowledge library.</div></div><div style={pill}>KENTAINERS KNOWLEDGE</div></div><div style={{display:"flex",gap:9,flexWrap:"wrap",marginTop:13}}>{technicalQuestions.map(q=><button key={q} onClick={()=>useQuestion(q)} style={chipStyle}>{q}</button>)}</div></section>
 <div style={{background:"rgba(255,255,255,.98)",border:`1px solid ${brand.line}`,borderRadius:22,boxShadow:"0 14px 40px rgba(0,47,91,.10)",overflow:"hidden",marginTop:16}}><section style={{padding:"19px 21px",borderBottom:`1px solid ${brand.line}`,background:`linear-gradient(180deg,#fff,${brand.pale})`}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:15,flexWrap:"wrap"}}><div><div style={{fontWeight:900,fontSize:17,color:brand.ink}}>Customer enquiry</div><div style={{fontSize:12,color:brand.muted,marginTop:3}}>Capture the customer and sales requirements so the Kentainers team can follow up.</div></div><div style={{display:"flex",alignItems:"center",gap:9}}>{enquiryId&&<span style={pill}>SAVED • {enquiryId}</span>}<button onClick={newEnquiry} disabled={loading} style={secondaryButton}>New enquiry</button></div></div>
 <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:10,marginTop:15}}><input value={customerName} onChange={e=>setCustomerName(e.target.value)} placeholder="Customer name" style={inputStyle}/><input type="email" value={customerEmail} onChange={e=>setCustomerEmail(e.target.value)} placeholder="Customer email" style={inputStyle}/><input type="tel" value={customerPhone} onChange={e=>setCustomerPhone(e.target.value)} placeholder="Customer phone number" style={inputStyle}/></div>
 <div style={{marginTop:14,padding:14,borderRadius:14,background:"#F8FCFE",border:`1px solid ${brand.line}`}}><div style={{fontSize:12,fontWeight:900,color:brand.ink,marginBottom:10}}>Sales requirement <span style={{fontWeight:500,color:brand.muted}}>— domestic and commercial applications supported</span></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(170px,1fr))",gap:9}}><input value={requirements.product} onChange={e=>setReq("product",e.target.value)} placeholder="Product / tank type" style={inputStyle}/><input value={requirements.capacity} onChange={e=>setReq("capacity",e.target.value)} placeholder="Capacity e.g. 5,000 L" style={inputStyle}/><select value={requirements.application} onChange={e=>setReq("application",e.target.value)} style={inputStyle}><option>Domestic & Commercial</option><option>Domestic</option><option>Commercial</option><option>Other / specify in chat</option></select><input value={requirements.location} onChange={e=>setReq("location",e.target.value)} placeholder="Delivery location" style={inputStyle}/><input value={requirements.quantity} onChange={e=>setReq("quantity",e.target.value)} placeholder="Quantity" style={inputStyle}/><input value={requirements.timeframe} onChange={e=>setReq("timeframe",e.target.value)} placeholder="Required by / timeframe" style={inputStyle}/></div></div></section>
 <section style={{padding:"8px 21px 18px",minHeight:390,maxHeight:560,overflowY:"auto",background:"#FCFEFF"}}>{messages.map((m,i)=><div key={i} style={{display:"flex",justifyContent:m.role==="user"?"flex-end":"flex-start",margin:"14px 0"}}><div style={{maxWidth:"82%",padding:"14px 16px",borderRadius:m.role==="user"?"18px 18px 5px 18px":"18px 18px 18px 5px",background:m.role==="user"?`linear-gradient(135deg,${brand.blue},${brand.sky})`:brand.light,color:m.role==="user"?"white":brand.ink}}><div style={{fontSize:10,fontWeight:900,opacity:.72,marginBottom:6}}>{m.role==="user"?"YOU":"KENTAINERS CHATBOT"}</div><div style={{whiteSpace:"pre-wrap",lineHeight:1.55,fontSize:14}}>{m.text}</div>{m.enquiryId?<div style={{marginTop:8,fontSize:10,color:brand.blue,fontWeight:900}}>ENQUIRY SAVED: {m.enquiryId}</div>:null}</div></div>)}{loading&&<div style={{color:brand.muted,fontSize:13,padding:"10px 2px"}}>Kentainers Chatbot is checking the knowledge base…</div>}</section>
 <section style={{padding:"16px 21px 21px",borderTop:`1px solid ${brand.line}`,background:"white"}}><div style={{display:"flex",gap:10,alignItems:"stretch"}}><input id="chat-input" value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="Ask about a product, price, dimensions, application or technical requirement…" style={{...inputStyle,flex:1,fontSize:14,padding:"14px 15px"}}/><button onClick={send} disabled={loading||!input.trim()} style={{minWidth:125,padding:"0 18px",border:0,borderRadius:11,background:loading||!input.trim()?"#B9C8D1":brand.navy,color:"white",fontWeight:900}}>{loading?"Checking…":"Ask Chatbot"}</button></div><div style={{fontSize:10,color:"#7A8990",marginTop:9}}>Answers are grounded in available Kentainers catalogue, technical library and website evidence. Confirm current commercial and engineering details before final quotation or installation.</div></section></div>
 <footer style={{textAlign:"center",padding:"18px 5px 0",fontSize:11,color:brand.muted}}>Kentainers Product Chatbot • Product & Technical Intelligence</footer></div></main>}
const cardStyle:CSSProperties={background:"rgba(255,255,255,.94)",border:`1px solid #D7E7F0`,borderRadius:17,padding:"17px 18px",boxShadow:"0 7px 24px rgba(0,47,91,.06)"};
const pill:CSSProperties={fontSize:10,fontWeight:900,color:"#0066A1",background:"#EAF6FB",padding:"7px 10px",borderRadius:999};
const inputStyle:CSSProperties={padding:"11px 12px",border:"1px solid #C8DCE7",borderRadius:10,outline:"none",background:"white",color:"#17324D",fontSize:14};
const chipStyle:CSSProperties={border:"1px solid #C8DDE8",background:"#F7FCFE",color:"#004F7C",borderRadius:999,padding:"9px 12px",fontSize:12,fontWeight:800,cursor:"pointer"};
const secondaryButton:CSSProperties={padding:"9px 13px",border:"1px solid #D7E7F0",borderRadius:10,background:"white",fontWeight:800,color:"#002F5B",cursor:"pointer"};
