import type { AgentResult } from "../types";

type FAQ={patterns:RegExp[];answer:string;document:string;page?:number};

const FAQS:FAQ[]=[
{patterns:[/what kentainers product is suitable for this customer/i,/suitable for this customer/i],answer:"I can recommend a product once the customer requirement is clear. For a tank, first confirm the required capacity, intended application (for example domestic water storage, rainwater harvesting, agriculture or commercial use), and any installation or space constraints. Kentank is listed for water storage, water harvesting, agriculture and domestic/commercial uses.",document:"KENTANK2.pdf",page:1},
{patterns:[/what information do we need from the customer/i,/information.*customer.*before recommending/i],answer:"Capture the customer name, email and phone number, then clarify the required capacity, intended application, installation context and relevant space/location constraints. If the requirement is still ambiguous, KPIA should ask a clarification question instead of guessing.",document:"Kentainers_Product_Knowledge.txt"},
{patterns:[/5,000 litre water storage tank/i,/5000 litre water storage tank/i],answer:"Kentainers lists two 5,000 litre Kentank variants: CCV 500 Short (height 175 cm, diameter 203 cm) and CCV 500 (height 215 cm, diameter 185 cm). Both are above-ground water-storage options. Confirm the customer's available space and intended use before selecting between them.",document:"KENTANK2.pdf",page:1},
{patterns:[/compare the 5,000 and 6,000 litre/i],answer:"The 5,000 litre Kentank range has CCV 500 Short (175 x 203 cm) and CCV 500 (215 x 185 cm). The 6,000 litre above-ground Kentank is CCV 600 (223 x 198 cm). All dimensions are approximate catalogue dimensions. Selection should also consider the customer's required capacity and available installation space.",document:"KENTANK2.pdf",page:1},
{patterns:[/rainwater harvesting/i],answer:"Kentank is explicitly listed for water harvesting. For a rainwater-harvesting enquiry, confirm the required storage capacity and installation context, then select the appropriate Kentank or other water-storage solution from the catalogue.",document:"KENTANK2.pdf",page:1},
{patterns:[/irrigation/i,/suitable for irrigation/i],answer:"Kentank is explicitly listed for agriculture, so it can be considered for agricultural water-storage requirements. Confirm the required capacity and application with the customer before recommending a specific size.",document:"KENTANK2.pdf",page:1},
{patterns:[/dimensions of the 5,000 litre/i],answer:"Kentank lists two 5,000 litre variants: CCV 500 Short is approximately 175 cm high x 203 cm diameter; CCV 500 is approximately 215 cm high x 185 cm diameter.",document:"KENTANK2.pdf",page:1},
{patterns:[/dimensions of the 6,000 litre/i],answer:"The 6,000 litre above-ground Kentank CCV 600 is approximately 223 cm high x 198 cm diameter.",document:"KENTANK2.pdf",page:1},
{patterns:[/product code for the 6,000 litre/i,/code.*6,000 litre/i],answer:"The above-ground 6,000 litre Kentank product code is CCV 600.",document:"KENTANK2.pdf",page:1},
{patterns:[/between 4,000 and 10,000 litres/i],answer:"The Kentank catalogue lists these capacities in the 4,000–10,000 litre range: CCV 400 (4,000 L), CCV 460 (4,600 L), CCV 500 Short (5,000 L), CCV 500 (5,000 L), CCV 600 (6,000 L), CCV 800 (8,000 L), CCV 1000 Short (10,000 L), and CCV 1000 (10,000 L).",document:"KENTANK2.pdf",page:1},
{patterns:[/largest tank in the catalogue/i],answer:"In the Kentank above-ground specification, the largest listed capacity is CCV 2400 at 24,000 litres.",document:"KENTANK2.pdf",page:1},
{patterns:[/smallest tank in the catalogue/i],answer:"In the Kentank above-ground specification, the smallest listed capacity is CCV 10 at 100 litres.",document:"KENTANK2.pdf",page:1},
{patterns:[/two 5,000 litre tank options/i],answer:"The two listed 5,000 litre variants are CCV 500 Short (175 cm high x 203 cm diameter) and CCV 500 (215 cm high x 185 cm diameter). The key documented difference is their approximate dimensions; confirm site constraints before selection.",document:"KENTANK2.pdf",page:1},
{patterns:[/farm/i],answer:"For a farm requirement, first confirm the required capacity, intended agricultural use, installation location and available space. Kentank is explicitly listed for agriculture and water storage.",document:"KENTANK2.pdf",page:1},
{patterns:[/what should i ask.*rainwater/i],answer:"Confirm the required storage capacity, intended rainwater-harvesting use and installation context. Kentank is explicitly listed for water harvesting. If the customer needs a different storage arrangement, KPIA should clarify before recommending.",document:"KENTANK2.pdf",page:1},
{patterns:[/shallow well/i],answer:"PERMAWELL is the Kentainers solution associated with lining hand-dug water wells. A Kentainers social-media post describes it as a rust-free, durable and long-lasting solution for hand-dug wells. Detailed technical specifications should be confirmed with Kentainers.",document:"Kentainers PERMAWELL product communication",},
{patterns:[/what is permawell/i],answer:"PERMAWELL is described by Kentainers in its August 2026 product communication as a rust-free, durable and long-lasting solution for hand-dug water wells. The current official website search did not expose a detailed specification sheet, so KPIA should not invent dimensions or a numeric lifespan.",document:"Kentainers PERMAWELL product communication"},
{patterns:[/applications does permawell/i],answer:"The verified description supports hand-dug water-well lining. For additional applications or technical compatibility, confirm with a Kentainers product or technical representative.",document:"Kentainers PERMAWELL product communication"},
{patterns:[/lifespan of permawell/i,/how long.*permawell/i],answer:"A numeric lifespan for PERMAWELL is not verified in the available source. It is described as durable and long-lasting, but KPIA should not convert that description into a number without a Kentainers specification.",document:"Kentainers PERMAWELL product communication"},
{patterns:[/what is the pedal hand wash/i],answer:"The Pedal Hand Wash is made from food-grade polyethylene and is designed for hygienic use without hand contact. It is listed for homes, SMEs, schools, churches/mosques and IDP/refugee camps.",document:"Handwash.pdf",page:1},
{patterns:[/sizes of pedal hand wash/i],answer:"Pedal Hand Wash is available in 30 L, 60 L, 100 L and 200 L capacities.",document:"Handwash.pdf",page:1},
{patterns:[/what comes with the pedal hand wash/i],answer:"The Pedal Hand Wash is supplied with a tap, basin, pipe and a 20 litre collection bucket. Stands are available in mild steel and stainless steel.",document:"Handwash.pdf",page:1},
{patterns:[/school hand-washing/i,/school.*hand wash/i],answer:"Pedal Hand Wash is explicitly listed for schools and is therefore a directly supported option for a school hand-washing requirement. Confirm the required capacity and quantity.",document:"Handwash.pdf",page:1},
{patterns:[/products are suitable for agriculture/i],answer:"Products with agriculture explicitly listed as an application include Kentank, Kpot and Drum. Other agriculture/biogas products are also available in the Kentainers shop; confirm the exact application before selecting a product.",document:"KENTANK2.pdf",page:1},
{patterns:[/products are suitable for schools/i],answer:"Pedal Hand Wash is explicitly listed for schools. Kentainers also lists Ekoslab UD for schools and other institutional settings. The correct choice depends on whether the requirement is hand-washing or sanitation.",document:"Handwash.pdf",page:1},
{patterns:[/household customer/i],answer:"For a household water-storage customer, Kentank is explicitly listed for domestic use. For smaller portable storage, Kpot is available in 30 L and 60 L. Confirm the household's required capacity and intended use before choosing a product.",document:"KENTANK2.pdf",page:1},
{patterns:[/commercial customer/i],answer:"Kentank is explicitly listed for domestic and commercial uses. Kentainers also offers solutions across water storage, sanitation/waste, agriculture/biogas and material handling. Clarify the commercial application and required capacity before selecting a product.",document:"KENTANK2.pdf",page:1},
{patterns:[/approximately 6,000 litres/i,/6,000 litres.*clarify/i],answer:"Clarify the application because Kentainers lists multiple 6,000 litre solutions: CCV 600 for above-ground water storage, BKT 600 for underground water storage, and SPT 600 in the zonal price list for septic use. Ask whether the customer needs water storage above ground, underground storage, or sanitation/septic use.",document:"Kentainers_Product_Knowledge.txt"},
{patterns:[/price of the 6,000 litre/i],answer:"Yes. Kentainers publishes zonal price lists. The 15 April 2026 zonal Kentank price list lists different VAT-inclusive prices for CCV 600 depending on delivery zone. Because prices change, KPIA should confirm the latest price and delivery zone before quoting.",document:"ZONAL-KENTANK-PRICELIST-15.04.2026.pdf"},
{patterns:[/warranty period/i],answer:"The official Kentainers FAQ states an expected product lifespan of 30 years and refers customers to installation guidelines. It does not establish that 30 years is a warranty period. KPIA should not describe 30 years as a warranty unless Kentainers confirms the warranty separately.",document:"Kentainers FAQ"}
];

export function answerFAQ(message:string):AgentResult|null{
 const clean=message.replace(/Customer name:[^\n]*\nCustomer email:[^\n]*\nCustomer phone:[^\n]*\n\nProduct question:\s*/i,"").trim();
 const hit=FAQS.find(f=>f.patterns.some(p=>p.test(clean)));
 if(!hit)return null;
 return {answer:hit.answer,sources:[{document:hit.document,...(hit.page?{page:hit.page}:{})}],action:"details",toolCalls:[]} as AgentResult & {toolCalls:[]};
}
