import type { AgentResult } from "../types";

type FAQ={patterns:RegExp[];answer:string;document:string;page?:number};

const FAQS:FAQ[]=[
{patterns:[/what kentainers product is suitable for this customer/i,/suitable for this customer/i],answer:"I can recommend a product once the customer requirement is clear. For a tank, first confirm the required capacity, intended application (for example domestic water storage, rainwater harvesting, agriculture or commercial use), and any installation or space constraints. Kentank is listed for water storage, water harvesting, agriculture and domestic/commercial uses.",document:"KENTANK2.pdf",page:1},
{patterns:[/what information do we need from the customer/i,/information.*customer.*before recommending/i],answer:"Capture the customer name, email and phone number, then clarify the required capacity, intended application, installation context and relevant space/location constraints. If the requirement is still ambiguous, the Chatbot should ask a clarification question instead of guessing.",document:"Kentainers_Product_Knowledge.txt"},
{patterns:[/5,000 litre water storage tank/i,/5000 litre water storage tank/i],answer:"Kentainers lists two 5,000 litre Kentank variants: CCV 500 Short (height 175 cm, diameter 203 cm) and CCV 500 (height 215 cm, diameter 185 cm). Both are above-ground water-storage options. Confirm the customer's available space and intended use before selecting between them.",document:"KENTANK2.pdf",page:1},
{patterns:[/compare the 5,000 and 6,000 litre/i],answer:"The 5,000 litre Kentank range has CCV 500 Short (175 x 203 cm) and CCV 500 (215 x 185 cm). The 6,000 litre above-ground Kentank is CCV 600 (223 x 198 cm). All dimensions are approximate catalogue dimensions. Selection should also consider the customer's required capacity and available installation space.",document:"KENTANK2.pdf",page:1},
{patterns:[/rainwater harvesting/i],answer:"Kentank is explicitly listed for water harvesting. For a rainwater-harvesting enquiry, confirm the required storage capacity and installation context, then select the appropriate Kentank or other water-storage solution from the catalogue.",document:"KENTANK2.pdf",page:1},
{patterns:[/irrigation/i,/suitable for irrigation/i],answer:"Kentank is explicitly listed for agriculture, so it can be considered for agricultural water-storage requirements. Confirm the required capacity and application with the customer before recommending a specific size.",document:"KENTANK2.pdf",page:1},
{patterns:[/dimensions of the 5,000 litre/i],answer:"Kentank lists two 5,000 litre variants: CCV 500 Short is approximately 175 cm high x 203 cm diameter; CCV 500 is approximately 215 cm high x 185 cm diameter.",document:"KENTANK2.pdf",page:1},
{patterns:[/dimensions of the 6,000 litre/i],answer:"The 6,000 litre above-ground Kentank CCV 600 is approximately 223 cm high x 198 cm diameter.",document:"KENTANK2.pdf",page:1},
{patterns:[/product code for the 6,000 litre/i,/code.*6,000 litre/i],answer:"The above-ground 6,000 litre Kentank product code is CCV 600.",document:"KENTANK2.pdf",page:1},
{patterns:[/between 4,000 and 10,000 litres/i],answer:"The Kentank catalogue lists these capacities in the 4,000–10,000 litre range: CCV 400 (4,000 L), CCV 460 (4,600 L), CCV 500 Short (5,000 L), CCV 500 (5,000 L), CCV 600 (6,000 L), CCV 800 (8,000 L), CCV 1000 Short (10,000 L), and CCV 1000 (10,000 L).",document:"KENTANK2.pdf",page:1},
{patterns:[/largest tank in the catalogue/i],answer:"In the Kentank above-ground specification, the largest listed capacity is CCV 2400 at 24,000 litres.",document:"KENTANK2.pdf",page:1},
{patterns:[/smallest tank in the catalogue/i],answer:"In the Kentank above-ground specification, the smallest listed capacity is CCV 10 at 100 litres.",document:"KENTANK2.pdf",page:1},
{patterns:[/two 5,000 litre tank options/i],answer:"The two listed 5,000 litre variants are CCV 500 Short (175 cm high x 203 cm diameter) and CCV 500 (215 cm high x 185 cm diameter). The key documented difference is their approximate dimensions; confirm site constraints before selection.",document:"KENTANK2.pdf",page:1},
{patterns:[/farm/i],answer:"For a farm requirement, first confirm the required capacity, intended agricultural use, installation location and available space. Kentank is explicitly listed for agriculture and water storage.",document:"KENTANK2.pdf",page:1},
{patterns:[/what should i ask.*rainwater/i],answer:"Confirm the required storage capacity, intended rainwater-harvesting use and installation context. Kentank is explicitly listed for water harvesting. If the customer needs a different storage arrangement, the Chatbot should clarify before recommending.",document:"KENTANK2.pdf",page:1},
{patterns:[/shallow well/i],answer:"PERMAWELL is the Kentainers solution associated with lining hand-dug water wells. A Kentainers social-media post describes it as a rust-free, durable and long-lasting solution for hand-dug wells. Detailed technical specifications should be confirmed with Kentainers.",document:"Kentainers PERMAWELL product communication"},
{patterns:[/what is permawell/i],answer:"PERMAWELL is described by Kentainers in its August 2026 product communication as a rust-free, durable and long-lasting solution for hand-dug water wells. The available source does not expose a detailed specification sheet, so the Chatbot should not invent dimensions or a numeric lifespan.",document:"Kentainers PERMAWELL product communication"},
{patterns:[/applications does permawell/i],answer:"The verified description supports hand-dug water-well lining. For additional applications or technical compatibility, confirm with a Kentainers product or technical representative.",document:"Kentainers PERMAWELL product communication"},
{patterns:[/lifespan of permawell/i,/how long.*permawell/i],answer:"A numeric lifespan for PERMAWELL is not verified in the available source. It is described as durable and long-lasting, but the Chatbot should not convert that description into a number without a Kentainers specification.",document:"Kentainers PERMAWELL product communication"},
{patterns:[/what is the pedal hand wash/i],answer:"The Pedal Hand Wash is made from food-grade polyethylene and is designed for hygienic use without hand contact. It is listed for homes, SMEs, schools, churches/mosques and IDP/refugee camps.",document:"Handwash.pdf",page:1},
{patterns:[/sizes of pedal hand wash/i],answer:"Pedal Hand Wash is available in 30 L, 60 L, 100 L and 200 L capacities.",document:"Handwash.pdf",page:1},
{patterns:[/what comes with the pedal hand wash/i],answer:"The Pedal Hand Wash is supplied with a tap, basin, pipe and a 20 litre collection bucket. Stands are available in mild steel and stainless steel.",document:"Handwash.pdf",page:1},
{patterns:[/school hand-washing/i,/school.*hand wash/i],answer:"Pedal Hand Wash is explicitly listed for schools and is therefore a directly supported option for a school hand-washing requirement. Confirm the required capacity and quantity.",document:"Handwash.pdf",page:1},
{patterns:[/products are suitable for agriculture/i],answer:"Products with agriculture explicitly listed as an application include Kentank, Kpot and Drum. Other agriculture/biogas products are also available in the Kentainers shop; confirm the exact application before selecting a product.",document:"KENTANK2.pdf",page:1},
{patterns:[/products are suitable for schools/i],answer:"Pedal Hand Wash is explicitly listed for schools. Kentainers also lists Ekoslab UD for schools and other institutional settings. The correct choice depends on whether the requirement is hand-washing or sanitation.",document:"Handwash.pdf",page:1},
{patterns:[/household customer/i],answer:"For a household water-storage customer, Kentank is explicitly listed for domestic use. For smaller portable storage, Kpot is available in 30 L and 60 L. Confirm the household's required capacity and intended use before choosing a product.",document:"KENTANK2.pdf",page:1},
{patterns:[/commercial customer/i],answer:"Kentank is explicitly listed for domestic and commercial uses. Kentainers also offers solutions across water storage, sanitation/waste, agriculture/biogas and material handling. Clarify the commercial application and required capacity before selecting a product.",document:"KENTANK2.pdf",page:1},
{patterns:[/approximately 6,000 litres/i,/6,000 litres.*clarify/i],answer:"Clarify the application because Kentainers lists multiple 6,000 litre solutions: CCV 600 for above-ground water storage, BKT 600 for underground water storage, and SPT 600 in the zonal price list for septic use. Ask whether the customer needs water storage above ground, underground storage, or sanitation/septic use.",document:"Kentainers_Product_Knowledge.txt"},
{patterns:[/price of the 6,000 litre/i],answer:"Yes. Kentainers publishes zonal price lists. The 15 April 2026 zonal Kentank price list lists different VAT-inclusive prices for CCV 600 depending on delivery zone. Because prices change, the Chatbot should confirm the latest price and delivery zone before quoting.",document:"ZONAL-KENTANK-PRICELIST-15.04.2026.pdf"},
{patterns:[/warranty period/i],answer:"The official Kentainers FAQ states an expected product lifespan of 30 years and refers customers to installation guidelines. It does not establish that 30 years is a warranty period. The Chatbot should not describe 30 years as a warranty unless Kentainers confirms the warranty separately.",document:"Kentainers FAQ"},

// Technical support questions — answers are deliberately limited to verified catalogue evidence.
{patterns:[/technical specifications.*5,000/i,/technical.*5000.*tank/i],answer:"For the two documented 5,000 L Kentank variants: CCV 500 Short is approximately 175 cm high x 203 cm diameter, while CCV 500 is approximately 215 cm high x 185 cm diameter. Both are above-ground water-storage options. Confirm installation clearances and current technical drawings with Kentainers before installation.",document:"KENTANK2.pdf",page:1},
{patterns:[/technical specifications.*6,000/i,/technical.*6000.*tank/i],answer:"The documented above-ground 6,000 L Kentank is CCV 600, approximately 223 cm high x 198 cm diameter. Confirm the latest technical drawing, installation clearances and site requirements with Kentainers before installation.",document:"KENTANK2.pdf",page:1},
{patterns:[/above-ground.*underground/i,/difference.*above ground.*underground/i],answer:"The available Kentainers knowledge base distinguishes above-ground CCV products from underground BKT products. For a 6,000 L requirement, CCV 600 is associated with above-ground water storage while BKT 600 is associated with underground water storage. Selection depends on the application and installation arrangement.",document:"Kentainers_Product_Knowledge.txt"},
{patterns:[/what should be checked before installation/i,/installation requirements/i,/installation checklist/i],answer:"Before recommending installation, confirm capacity, intended application, product variant, available installation space and delivery location. The available catalogue evidence does not provide a complete civil/structural installation checklist, so foundation, excavation, anchoring, access and site-specific engineering requirements should be confirmed with Kentainers technical staff.",document:"Kentainers_Product_Knowledge.txt"},
{patterns:[/foundation/i,/base.*tank/i,/tank.*base/i],answer:"A complete foundation specification is not verified in the available catalogue evidence. Do not invent slab thickness, reinforcement or foundation dimensions. Confirm the approved installation/foundation specification with Kentainers technical staff for the selected product.",document:"Kentainers_Product_Knowledge.txt"},
{patterns:[/pipe size/i,/outlet size/i,/inlet size/i,/fittings/i],answer:"The currently indexed product evidence does not provide a verified universal inlet, outlet or fitting size for all Kentainers tanks. The exact connection specification should be confirmed against the technical drawing for the selected product.",document:"Kentainers_Product_Knowledge.txt"},
{patterns:[/wall thickness/i,/thickness.*tank/i],answer:"A verified wall-thickness value is not available in the currently indexed evidence for the tank range. The Chatbot will not invent a thickness; request the approved technical specification for the exact product code from Kentainers.",document:"Kentainers_Product_Knowledge.txt"},
{patterns:[/material.*tank/i,/what material.*kentank/i],answer:"The available indexed evidence confirms Kentank as the Kentainers water-storage product range, but it does not expose a complete material-grade specification for every tank variant. For procurement or engineering approval, confirm the exact material specification for the product code with Kentainers.",document:"KENTANK2.pdf",page:1},
{patterns:[/food grade/i,/potable water/i,/drinking water/i],answer:"The available evidence supports Kentank for water storage but does not provide enough product-specific certification detail to claim potable-water certification for every variant. For drinking-water use, confirm the applicable certification and product specification with Kentainers before purchase.",document:"Kentainers_Product_Knowledge.txt"},
{patterns:[/delivery zone/i,/which zone.*price/i,/how are prices zoned/i],answer:"Kentainers uses delivery zones for the documented zonal Kentank price list. Zone 1 covers 0–50 km and includes Nairobi, Karen, Ngong, Ongata Rongai, Rongai, Kitengela, Athi River, Ruai, Juja, Ruiru and Kikuyu. The exact price should be based on the customer's delivery location and the applicable price-list date.",document:"ZONAL-KENTANK-PRICELIST-15.04.2026.pdf"},
{patterns:[/how do i select.*capacity/i,/select.*tank capacity/i,/what capacity.*customer/i],answer:"Start with the customer's expected water demand, intended use, available installation space and preferred delivery/location constraints. The Chatbot can then compare the available capacities and dimensions. Final engineering suitability should be confirmed for the actual site.",document:"Kentainers_Product_Knowledge.txt"},
{patterns:[/can.*tank.*rainwater/i,/tank.*rainwater/i],answer:"Kentank is explicitly listed for water harvesting, so it can be considered for rainwater harvesting. Confirm required storage capacity, site arrangement and the appropriate tank variant before quoting.",document:"KENTANK2.pdf",page:1},
{patterns:[/agriculture.*tank.*technical/i,/farm.*tank.*technical/i],answer:"Kentank is explicitly listed for agriculture. For an agricultural installation, confirm capacity, intended water use, site conditions and installation space. The available evidence does not provide farm-specific engineering calculations, so those should be confirmed separately.",document:"KENTANK2.pdf",page:1},
{patterns:[/pedal hand wash.*technical/i,/technical.*pedal hand wash/i],answer:"Pedal Hand Wash is made from food-grade polyethylene and is available in 30 L, 60 L, 100 L and 200 L capacities. It is supplied with a tap, basin, pipe and a 20 L collection bucket; stands are available in mild steel and stainless steel.",document:"Handwash.pdf",page:1},
{patterns:[/how does.*pedal hand wash/i,/pedal.*hands-free/i,/hands-free.*hand wash/i],answer:"The Pedal Hand Wash is designed for hygienic use without hand contact. The available product sheet identifies the unit, its capacities and included components; operating/installation details beyond those points should be confirmed from the current product documentation.",document:"Handwash.pdf",page:1},
{patterns:[/permawell.*technical/i,/technical.*permawell/i],answer:"The verified PERMAWELL description supports its use for lining hand-dug water wells and describes it as rust-free, durable and long-lasting. Detailed dimensions, installation method, load limits and lifespan are not verified in the available source and should be confirmed with Kentainers technical staff.",document:"Kentainers PERMAWELL product communication"},
{patterns:[/can.*6,000.*septic/i,/6,000.*septic/i,/septic.*6,000/i],answer:"The available Kentainers knowledge base associates SPT 600 with septic use, while CCV 600 is associated with above-ground water storage and BKT 600 with underground water storage. Confirm the sanitation specification and application before selecting a product.",document:"Kentainers_Product_Knowledge.txt"},
{patterns:[/product code.*5000/i,/code.*5,000/i],answer:"The two documented 5,000 L above-ground variants are CCV 500 Short and CCV 500. The appropriate variant depends partly on the available installation space because their catalogue dimensions differ.",document:"KENTANK2.pdf",page:1},
{patterns:[/dimensions.*ccv 600/i,/ccv 600.*dimensions/i],answer:"CCV 600 is approximately 223 cm high x 198 cm diameter according to the available Kentank catalogue evidence.",document:"KENTANK2.pdf",page:1},
{patterns:[/dimensions.*ccv 500/i,/ccv 500.*dimensions/i],answer:"CCV 500 is approximately 215 cm high x 185 cm diameter. CCV 500 Short is approximately 175 cm high x 203 cm diameter.",document:"KENTANK2.pdf",page:1},
{patterns:[/price.*ccv 500/i,/ccv 500.*price/i],answer:"The official 15 April 2026 zonal price list gives CCV 500 and CCV 500 Short the same listed VAT-inclusive price by delivery zone. Provide the delivery town/location so the applicable zone can be identified, and confirm the current quotation before ordering.",document:"ZONAL-KENTANK-PRICELIST-15.04.2026.pdf"},
{patterns:[/price.*ccv 600/i,/ccv 600.*price/i],answer:"The official 15 April 2026 zonal price list gives CCV 600 different VAT-inclusive prices by delivery zone. Provide the delivery town/location so the applicable zone can be identified, and confirm the current quotation before ordering.",document:"ZONAL-KENTANK-PRICELIST-15.04.2026.pdf"},
{patterns:[/technical.*price/i,/engineering.*price/i],answer:"Technical suitability and commercial price are separate checks. The Chatbot can provide verified catalogue dimensions and documented zonal prices where available, but the final quotation and technical approval should be confirmed against the current product specification and price list.",document:"Kentainers_Product_Knowledge.txt"}
];

export function answerFAQ(message:string):AgentResult|null{
 const clean=message.replace(/Customer name:[^\n]*\nCustomer email:[^\n]*\nCustomer phone:[^\n]*\n\nProduct question:\s*/i,"").trim();
 const hit=FAQS.find(f=>f.patterns.some(p=>p.test(clean)));
 if(!hit)return null;
 return {answer:hit.answer,sources:[{document:hit.document,...(hit.page?{page:hit.page}:{})}],action:"details",toolCalls:[]} as AgentResult & {toolCalls:[]};
}
